# This workflow will upload statics to AWS S3 on manual triggers

name: Upload Static

on:
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - static/**

concurrency: {{ github.head_ref ||  github.ref }}

env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: 22
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

jobs:
  collectstatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload Static
        uses: appleboy/ssh-action@master
        with:
          host: $SSH_HOST
          port: $SSH_PORT
          username: $SSH_USERNAME
          password: $SSH_PASSWORD
          script: |
            cd /home/berkay/Resume-Django-Web-App
            docker exec app_resume python manage.py collectstatic --noinput
