# This workflow will upload statics to AWS S3 on manual triggers

name: Upload Static

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to Server"]
    types:
      - completed


env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: 22
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

jobs:
  collectstatic:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v14
        id: verify-changed-files
        with:
          files: |
             static/**

      - name: Checkout code
        if: success()
        uses: actions/checkout@v3

      - name: Upload Static
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: $SSH_HOST
          port: $SSH_PORT
          username: $SSH_USERNAME
          password: $SSH_PASSWORD
          script: |
            cd /home/berkay/Resume-Django-Web-App
            docker exec app_resume python manage.py collectstatic --noinput
